### ISSUE TITLE
reset_grads() and reset_grads_and_moms()

### ISSUE THREAD

**Issue by dineshbvadhia** [Philip-Bachman/NN-Python#1]
In NLModels.py, the function infer_context_vectors() calls reset_grads() and reset_grads_and_moms() which are missing.

However, they are probably not required because on function exit, all variables are rest automatically by python.

**Comment by Philip-Bachman** [comment]
I corrected these function calls to the appropriate ones for these layer instances. The reset functions clears value that are written to momentum and gradient accumulators that get updated during feedforward and backprop.
