### ISSUE TITLE
Extra sentence vector

### ISSUE THREAD

**Issue by dineshbvadhia** [Philip-Bachman/NN-Python#2]
If N sentences are processed by NLModels, but infer_context_vectors returns N+1 sentence vectors?

Are the sentence vectors in "params" as Wm?

**Comment by Philip-Bachman** [comment]
The sentence vectors are in layer.params['Wb'] for the layer returned by the context vector inference method. The parameter Wm is for learning context-sensitive element-wise rescaling of the word vectors. Wm will only be used when layer.do_rescale is True.

If you want to train 'k' context vectors, they should be trained and returned in params['Wb'][0:k-1]. The extra rows are used to avoid awkward behavior in Numpy when dealing with arrays with one or more dimensions with size 1.

**Comment by dineshbvadhia** [comment]
Are the trained 'k' context vectors in the numpy array in the same order as the input sentences?
