### ISSUE TITLE
test_pv_model() and test_w2v_model() test examples

### ISSUE THREAD

**Issue by dineshbvadhia** [Philip-Bachman/NN-Python#6]
In NLModels.py, the test examples include code similar to:

[s_keys, n_keys, s_words, n_words] = some_nearest_words( k2w, 10, \
        W1=pvm.word_layer.params['W'], W2=None)
for w in range(10):
        print("{0:s}: {1:s}".format(s_words[w],", ".join(n_words[w])))

I'm guessing that this code is not part of the "Train all parameters using the training set phrases" - is that correct or did I miss something?

**Comment by Philip-Bachman** [comment]
This is to display some "diagnostics" during training. It finds the word vectors most similar to some other word vectors and writes the result to stdout, to check if training is doing something reasonable. It isn't part of training and doesn't cause any updates to the model.
