### ISSUE TITLE
Compilation comment

### ISSUE THREAD

**Issue by nouiz** [Philip-Bachman/NN-Python#8]
I found on reddit some information that your compilation time was hours. Just to let you know, we got many compilation speed up in the last few mounts in Theano. Be sure to update your version to the latest development version. We got one case with scan from 5h30 to 30m for example.

If it is still slow after the update, just to help us, can you give the output of your script (it just need to compile all Theano functions, it don't need to run them) with those Theano flags and give me the output? Just to know if your case have the same pattern as we see here.

profile=True

and

optimizer_profile=True

**Comment by Philip-Bachman** [comment]
Yes, Pierre Luc's comment was based on some of my past experience. The
compilation time for my scan-based code has gotten much better in the past
couple of months. My models that previously took ~90 minutes are down
around 30 minutes now. Thanks for your ongoing work.

**Comment by nouiz** [comment]
ok, so I'll close this here, as I don't think it belong here. thanks
